//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Demis2000.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define ID_ROWCOL                       101
#define IDD_PRJFORM                     101
#define IDP_FAILED_TO_CREATE            102
#define ID_AXEDIT                       102
#define CG_IDD_INFOBAR                  104
#define CG_ID_VIEW_INFOBAR              105
#define CG_IDD_PROJECTBAR               106
#define CG_ID_VIEW_PROJECTBAR           107
#define IDR_DASMVIEW                    108
#define IDR_DUMPVIEW                    109
#define IDR_REGSVIEW                    110
#define ID_INC_ADD                      111
#define ID_INC_DEL                      112
#define ID_ARCH_STATUS                  113
#define ID_INSTR_COUNTER                115
#define ID_FPS                          116
#define IDR_MAINFRAME                   128
#define IDR_PRJTYPE                     129
#define IDR_ASSMTYPE                    130
#define IDR_ARCHTYPE                    131
#define IDR_DEBUGTYPE                   132
#define IDR_MAINFRAMEC                  132
#define IDR_ARCHTYPEC                   133
#define IDD_DUMPCFG                     142
#define IDR_INFOFRAME                   145
#define IDI_CLOSEDFOLDER                147
#define IDI_OPENEDFOLDER                148
#define IDR_INCTYPE                     149
#define IDM_PRJPOPUP                    150
#define IDR_ASSMTYPE_ADD                155
#define IDR_PRJTYPE_ADD                 156
#define IDD_EMULATORCFG                 156
#define IDR_ARCHTYPE_ADD                157
#define IDB_RGATA                       157
#define IDR_DEBUGTYPE_ADD               158
#define IDR_CONTEXT_DEBUG               167
#define IDC_CAPTION                     1000
#define IDC_ADDRESS                     1001
#define IDC_SEGMENT                     1006
#define IDC_INFOEDIT                    1008
#define IDC_LISTTEXT                    1009
#define IDC_LISTLIB                     1010
#define IDC_ADDTEXT                     1011
#define IDC_DELTEXT                     1012
#define IDC_ADDLIB                      1013
#define IDC_DELLIB                      1014
#define IDC_LISTOBJ                     1015
#define IDC_ADDOBJ                      1016
#define IDC_DELOBJ                      1017
#define IDC_FINDARCH                    1019
#define IDC_ARCHOPEN                    1020
#define IDC_ARCHNAME                    1021
#define IDC_LABELTEXT                   1037
#define IDC_ROMSIZE                     1037
#define IDC_FIXCHECK                    1038
#define IDC_RAMSTART                    1038
#define IDC_RAMSIZE                     1039
#define IDC_ROMSTART                    1040
#define IDC_HIDECHECK                   1041
#define IDC_TAKTFREQ                    1041
#define IDC_CAPTION_TEXT                1059
#define IDC_FREEPIN_1                   1060
#define IDC_FREEPIN_0                   1061
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_ARCH_NEW                     32772
#define ID_ARCH_OPEN                    32774
#define ID_ARCH_SAVE                    32775
#define ID_ARCH_CLOSE                   32776
#define ID_                             32777
#define ID_ASSEMBLE                     32788
#define ID_RUN                          32791
#define ID_DEBUG                        32792
#define ID_BREAK                        32793
#define ID_STEPINTO                     32799
#define ID_STEPOVER                     32800
#define ID_DASMALL                      32803
#define ID_ASM_NEW                      32804
#define ID_ASM_SAVE                     32805
#define ID_PRJ_ADDFILE                  32820
#define ID_FILE_ADD                     32821
#define ID_FILE_DELETE                  32822
#define ID_PRJ_SAVE                     32823
#define ID_PRJ_OPEN                     32824
#define ID_PRJ_NEW                      32825
#define ID_0                            32826
#define ID_PRJ_ASSEMBLE                 32827
#define ID_SOURCE_OPEN                  32828
#define ID_SOURCE_DEL                   32829
#define ID_ARCH_DEL                     32831
#define ID_SOURCE_ADD                   32832
#define ID_ARCH_ADD                     32833
#define ID_LIB_ADD                      32834
#define ID_OBJ_ADD                      32835
#define ID_OBJ_DEL                      32836
#define ID_LIB_DEL                      32837
#define ID_SOURCE_NEW                   32839
#define ID_OBJ_NEW                      32840
#define ID_RUNTO                        32845
#define ID_EMULATORCFG                  32849
#define ID_FILE_MRU_PRJ1                32850
#define ID_FILE_MRU_PRJ2                32851
#define ID_FILE_MRU_PRJ3                32852
#define ID_FILE_MRU_PRJ4                32853
#define ID_ARCHELEM_DEL                 32861
#define ID_ARCHMODE                     32873
#define ID_CONSTRMODE                   32874
#define ID_NEW_ADDRESS                  32876
#define ID_BUILD                        32880
#define ID_LINK                         32881
#define ID_LINK_FLAG                    32882
#define ID_MENUITEM32889                32889
#define ID_VOID                         32891
#define ID_INC_OPEN                     32899
#define ID_ADD_ELEMENT0                 32900
#define ID_ADD_ELEMENT255               33155
#define ID_CONTAINS_ENTRYPOINT          33156
#define ID_TESTDEL                      33157

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32903
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
