#****************************************************************************

!ifdef MASTER_MAKE
BUILD_BITS=32
BUILD_TYPE=base
!INCLUDE $(DDKROOT)\master.mk
!endif

CFLAGS     = -DWIN32 -DCON -Di386 -D_X86_ -D_NTWIN -W3 -Gs
CVXDFLAGS  = -Zdp -Gs -c -DIS_32 -Zl -ID:\98ddk\inc\win98
LFLAGS     = -machine:i386 -debug:none -subsystem:console kernel32.lib 
AFLAGS     = -coff -DBLD_COFF -DIS_32 -W2 -c -Cx -DMASM6 -ID:\98ddk\inc\win98


all: direxist bin\DirBeep.VxD

direxist:
        if not exist bin\nul    md bin

bin\main.obj: main.c
        cl $(CVXDFLAGS) -Fo$@ %s

bin\DirBeep.obj: DirBeep.asm
        ml $(AFLAGS) -Fo$@ %s

bin\dio.obj: dio.asm
        ml -coff -DBLD_COFF -W2 -c -Cx -DMASM6 -DSEGNUM=1 -ID:\98ddk\inc\win98 -Fo$@ %s

#-MACHINE:i386 -DEBUG:FULL -PDB:NONE

bin\DirBeep.vxd: bin\main.obj bin\DirBeep.obj bin\dio.obj\
                  DirBeep.def
        echo >NUL @<<DirBeep.crf
-MACHINE:i386 -DEBUG:NONE -PDB:NONE 
-DEF:DirBeep.def -OUT:bin\DirBeep.vxd -MAP:bin\DirBeep.map
-VXD vxdwraps.clb bin\DirBeep.obj bin\main.obj bin\dio.obj
<<
        link @DirBeep.crf /LIBPATH:D:\98DDK\lib
        cd bin
        mapsym DirBeep
        cd ..

clean:
		-@del bin\*.obj
		-@del bin\*.vxd
		-@del bin\*.exe
		-@del bin\*.exp
		-@del bin\*.map
		-@del bin\*.sym
		-@del bin\*.lib
		-@rd  bin
		-@del *.pdb
